### ISSUE TITLE
Unable to compile Reqwest via nix-shell.

### ISSUE THREAD

**Issue by pwnwriter** [srid/rust-nix-template#31]
I've a simple project where I'm using reqwest and ring. 

`Cargo.toml`
```toml
[dependencies]
reqwest = { version = "0.11.24", features = ["blocking", "rustls-tls"], default-features = false }
ring = "0.17.8"
```

`main.rs`
```rust
fn main(){
     let client = reqwest::blocking::Client::new();
    dbg!(client);
}
```
I do have `ld` but the issue still persists, Do you have any suggestion? Can understand it doesn't relate to the flake itself. 

<img width="978" alt="Screenshot 2024-03-03 at 7 14 37 AM" src="https://github.com/srid/rust-nix-template/assets/90331517/ec51d5bc-c828-4a71-9aa7-d3ff1d557c8b">
